spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
#  datasource:
#    url: ${MYSQL_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
  datasource:
    url: jdbc:h2:file:~/testdb;MODE=MySQL
    #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:


  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  #  issuer: ${JWT_ISSUER}
  #  salt: ${JWT_SALT}
  access-token:
    expiretime: ${JWT_ACCESS_TOKEN_EXPIRETIME}
  refresh-token:
    expiretime: ${JWT_REFRESH_TOKEN_EXPIRETIME}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_BUCKET_REGION}
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

firebase:
  config:
    file: ${FIREBASE_JSON_PATH}