spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:file:~/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
#  issuer: ${JWT_ISSUER}
#  salt: ${JWT_SALT}
  access-token:
    expiretime: ${JWT_ACCESS_TOKEN_EXPIRETIME}
  refresh-token:
    expiretime: ${JWT_REFRESH_TOKEN_EXPIRETIME}